spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/iam?currentSchema=person
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
logging.level.root=INFO
logging.level.com.imap=DEBUG
