spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/iam?currentSchema=person
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
logging.level.root=WARN
logging.level.com.imap=INFO
